<a href="https://colab.research.google.com/github/a01038007367-pixel/-/blob/main/5_%EA%B4%80r_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

In [ ]:
A={1,2,3}
B={2,3,4}
R={(1,2),(2,3),(3,2),(3,4)}
print("관계 R:", R)

관계 R: {(2, 3), (3, 2), (1, 2), (3, 4)}


In [ ]:
A_list=sorted(A)
B_list=sorted(B)

relation_matrix=np.zeros((len(A_list), len(B_list)), dtype=int)

for i,a in enumerate(A_list):
  for j, b in enumerate(B_list):
    if (a,b) in R:
      relation_matrix[i,j]=1

print("관계 행렬(rows:A, columns:B):")
print(relation_matrix)


관계 행렬(rows:A, columns:B):
[[1 0 0]
 [0 1 0]
 [1 0 1]]


In [ ]:
#R:A->B
#S:B_>C
C={'x','y'}
S={(2,'x'),(3,'y'),(4,'x')}

composed_relation=set()

for(a,b1) in R:
  for(b2,c) in S:
    if b1==b2:
      composed_relation.add((a,c))

print("\n합성 관계 RXS:", composed_relation)


합성 관계 RXS: {(2, 'y'), (3, 'x'), (1, 'x')}
